### ISSUE TITLE
Cupper or MDN Fiori?

### ISSUE THREAD

**Issue by jwhitlock** [schalkneethling/mdn-fiori#1]
There are many [mentions of Cupper](https://github.com/schalkneethling/mdn-fiori/search?utf8=✓&q=cupper&type=) in the repo, including in CONTRIBUTING.md. Is the conversion to an MDN project complete?

**Comment by schalkneethling** [comment]
Well, it is built on [Cupper from the Paciello Group](https://github.com/ThePacielloGroup/cupper) and, in order to be able to get future updates I cannot mess around to much with the project files.

**Comment by jwhitlock** [comment]
OK. I've read the [upstream docs](https://thepaciellogroup.github.io/cupper/patterns/setup/). This is a strange project (not clearly splitting the engine from the content), but I think you've followed the instructions correctly to maximize the ability to refresh in the future.
