### ISSUE TITLE
LICENSE Copyright Heydon Pickering

### ISSUE THREAD

**Issue by jwhitlock** [schalkneethling/mdn-fiori#2]
Can this be changed to Mozilla, or to a dual copyright?

**Comment by schalkneethling** [comment]
I would say Cupper is licensed under MIT but, the content built on top of it can either be Creative Commons or MPL-2

**Comment by jwhitlock** [comment]
I see a few options:

* Move LICENSE to LICENSE-cupper. Create a LICENSE that says "This part is covered by this license, this part by this license", and add the license statement for the content. I think GitHub will claim the license isn't an open source license, since it will just look at LICENSE
* Amend the statement in license to state that some content is covered by the MIT License, and then add the text of a second license below. Manually merge the file as upstream changes. This is the route suggested by https://softwareengineering.stackexchange.com/questions/177768/how-do-i-correctly-sub-license-a-library-that-is-under-the-mit-license.
* Accept the MIT License for our stuff as well. Amend the copyright notice to add a second copyright, "Copyright (c) 2018 Mozilla", and manually merge just that line in the future.

We may want to include something in the README, CONTRIBUTING explaining the situation, which will probably be confusing to outside contributors or later staff.  An upstream issue might also be needed.

**Comment by schalkneethling** [comment]
@jwhitlock I have made some updates. Not sure this covers all of our basis, but let me know your thoughts. Thanks!

**Comment by jwhitlock** [comment]
I think this works for licensing, thanks!
